services:
  cloudflare-warp-proxy:
    image: seiry/cloudflare-warp-proxy
    # image: ghcr.io/seiry/cloudflare-warp-proxy
    network_mode: bridge
    ports:
      - 40000:40000
    restart: unless-stopped
    # environment:
    #   - LICENSE=  # use your own key, for warp+

    # to enroll into a Zero Trust org, mount a full MDM
    # config. see README "managed deployment (Zero Trust)"
    # volumes:
    #   - ./mdm.xml:/var/lib/cloudflare-warp/mdm.xml:ro
    logging:
      driver: json-file
      options:
        max-size: 1m
